//go:build linux

package wayland

// libwayland_text_input.go implements the optional zwp_text_input_v3 protocol.
//
// The protocol is intentionally modelled as a transaction: preedit, commit,
// and delete-surrounding events are accumulated until done(serial), then one
// Go callback receives the complete update. This prevents observers from
// seeing partially-applied state and gives the platform adapter one place to
// enforce UTF-8 ranges and committed-text de-duplication.

import (
	"fmt"
	"math"
	"runtime"
	"sync"
	"unicode/utf8"
	"unsafe"

	"github.com/go-webgpu/goffi/ffi"
	"github.com/gogpu/gpucontext"
)

// TextInputUpdate is one atomic zwp_text_input_v3 done transaction. The
// boolean fields distinguish an absent event from an event carrying an empty
// string (both are meaningful for preedit and commit).
type TextInputUpdate struct {
	HasPreedit   bool
	PreeditText  string
	CursorBegin  int32
	CursorEnd    int32
	HasCommit    bool
	CommitText   string
	HasDelete    bool
	DeleteBefore uint32
	DeleteAfter  uint32
}

type textInputPending struct {
	hasPreedit   bool
	preeditText  string
	cursorBegin  int32
	cursorEnd    int32
	commitSet    bool
	commitText   string
	deleteSet    bool
	deleteBefore uint32
	deleteAfter  uint32
}

// textInputInterfaces contains scanner-compatible descriptors for the two
// unstable-v3 protocol interfaces. No descriptor is exported by
// libwayland-client because this protocol is generated by applications.
var textInputInterfaces struct {
	once sync.Once

	manager cWlInterface
	text    cWlInterface

	managerMethods [2]cWlMessage
	textMethods    [8]cWlMessage
	textEvents     [6]cWlMessage
	nullTypes      [8]uintptr
}

func initTextInputInterfaces() {
	textInputInterfaces.once.Do(func() {
		nt := uintptr(unsafe.Pointer(&textInputInterfaces.nullTypes[0]))

		textInputInterfaces.managerMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		textInputInterfaces.managerMethods[1] = cWlMessage{cstr("get_text_input\x00"), cstr("no\x00"), nt}
		textInputInterfaces.manager = cWlInterface{
			Name:        cstr("zwp_text_input_manager_v3\x00"),
			Version:     1,
			MethodCount: 2,
			Methods:     uintptr(unsafe.Pointer(&textInputInterfaces.managerMethods[0])),
		}

		textInputInterfaces.textMethods[0] = cWlMessage{cstr("destroy\x00"), cstr("\x00"), nt}
		textInputInterfaces.textMethods[1] = cWlMessage{cstr("enable\x00"), cstr("\x00"), nt}
		textInputInterfaces.textMethods[2] = cWlMessage{cstr("disable\x00"), cstr("\x00"), nt}
		textInputInterfaces.textMethods[3] = cWlMessage{cstr("set_surrounding_text\x00"), cstr("suu\x00"), nt}
		textInputInterfaces.textMethods[4] = cWlMessage{cstr("set_text_change_cause\x00"), cstr("u\x00"), nt}
		textInputInterfaces.textMethods[5] = cWlMessage{cstr("set_content_type\x00"), cstr("uu\x00"), nt}
		textInputInterfaces.textMethods[6] = cWlMessage{cstr("set_cursor_rectangle\x00"), cstr("iiii\x00"), nt}
		textInputInterfaces.textMethods[7] = cWlMessage{cstr("commit\x00"), cstr("\x00"), nt}

		textInputInterfaces.textEvents[0] = cWlMessage{cstr("enter\x00"), cstr("\x00"), nt}
		textInputInterfaces.textEvents[1] = cWlMessage{cstr("leave\x00"), cstr("\x00"), nt}
		textInputInterfaces.textEvents[2] = cWlMessage{cstr("preedit_string\x00"), cstr("sii\x00"), nt}
		textInputInterfaces.textEvents[3] = cWlMessage{cstr("commit_string\x00"), cstr("s\x00"), nt}
		textInputInterfaces.textEvents[4] = cWlMessage{cstr("delete_surrounding_text\x00"), cstr("uu\x00"), nt}
		textInputInterfaces.textEvents[5] = cWlMessage{cstr("done\x00"), cstr("u\x00"), nt}
		textInputInterfaces.text = cWlInterface{
			Name:        cstr("zwp_text_input_v3\x00"),
			Version:     1,
			MethodCount: 8,
			Methods:     uintptr(unsafe.Pointer(&textInputInterfaces.textMethods[0])),
			EventCount:  6,
			Events:      uintptr(unsafe.Pointer(&textInputInterfaces.textEvents[0])),
		}
	})
}

var (
	textInputListener     [6]uintptr
	textInputListenerOnce sync.Once
	textInputHandlesMu    sync.Mutex
	textInputHandles      = make(map[uintptr]*LibwaylandHandle)
)

func initTextInputListener() {
	textInputListenerOnce.Do(func() {
		textInputListener[0] = ffi.NewCallback(textInputEnterCb)
		textInputListener[1] = ffi.NewCallback(textInputLeaveCb)
		textInputListener[2] = ffi.NewCallback(textInputPreeditCb)
		textInputListener[3] = ffi.NewCallback(textInputCommitCb)
		textInputListener[4] = ffi.NewCallback(textInputDeleteCb)
		textInputListener[5] = ffi.NewCallback(textInputDoneCb)
	})
}

// SetupTextInput binds the optional zwp_text_input_manager_v3 global and
// creates one text-input object for this handle's wl_seat. A missing global or
// seat is not an error: callers use HasTextInput to discover support.
func (h *LibwaylandHandle) SetupTextInput(name, version uint32) error {
	if h == nil || name == 0 || version == 0 || h.inputSeat == 0 {
		return nil
	}
	initTextInputInterfaces()
	initTextInputListener()

	v := version
	if v > 1 {
		v = 1
	}

	h.displayMu.Lock()
	defer h.displayMu.Unlock()
	h.textInputMu.Lock()
	alreadySupported := h.textInputSupported
	h.textInputMu.Unlock()
	if alreadySupported {
		return nil
	}

	manager, err := h.registryBind(name, unsafe.Pointer(&textInputInterfaces.manager), v)
	if err != nil {
		return fmt.Errorf("wayland: failed to bind zwp_text_input_manager_v3: %w", err)
	}
	textInput, err := h.marshalConstructorObj(
		manager, 1, unsafe.Pointer(&textInputInterfaces.text), h.inputSeat,
	)
	if err != nil {
		h.proxyDestroy(manager)
		return fmt.Errorf("wayland: failed to create zwp_text_input_v3: %w", err)
	}

	textInputHandlesMu.Lock()
	textInputHandles[textInput] = h
	textInputHandlesMu.Unlock()
	if err := h.addListener(textInput, uintptr(unsafe.Pointer(&textInputListener[0]))); err != nil {
		textInputHandlesMu.Lock()
		delete(textInputHandles, textInput)
		textInputHandlesMu.Unlock()
		h.proxyDestroy(textInput)
		h.proxyDestroy(manager)
		return fmt.Errorf("wayland: failed to add zwp_text_input_v3 listener: %w", err)
	}

	h.textInputMu.Lock()
	h.textInputManager = manager
	h.textInput = textInput
	h.textInputMu.Unlock()
	if err := h.flushWithRetry(); err != nil {
		textInputHandlesMu.Lock()
		delete(textInputHandles, textInput)
		textInputHandlesMu.Unlock()
		h.proxyDestroy(textInput)
		h.proxyDestroy(manager)
		h.textInputMu.Lock()
		h.textInputManager = 0
		h.textInput = 0
		h.textInputMu.Unlock()
		return err
	}
	h.textInputMu.Lock()
	h.textInputSupported = true
	h.textInputMu.Unlock()
	return nil
}

// HasTextInput reports whether this connection bound zwp_text_input_v3.
func (h *LibwaylandHandle) HasTextInput() bool {
	if h == nil {
		return false
	}
	h.textInputMu.Lock()
	defer h.textInputMu.Unlock()
	return h.textInputSupported && h.textInput != 0
}

// TextInputEnabled reports the protocol-side enabled state.
func (h *LibwaylandHandle) TextInputEnabled() bool {
	if h == nil {
		return false
	}
	h.textInputMu.Lock()
	defer h.textInputMu.Unlock()
	return h.textInputEnabled
}

// MarkTextInputEnter and MarkTextInputLeave update protocol focus state from
// callbacks. Leave invalidates all previously sent state and disables the
// protocol object; the platform adapter decides whether to replay it after a
// subsequent enter.
func (h *LibwaylandHandle) MarkTextInputEnter() {
	if h == nil {
		return
	}
	h.textInputMu.Lock()
	h.textInputEntered = true
	// The v3 protocol invalidates enable/content state on enter. Force the
	// next platform replay to issue enable again even if the app left IME
	// logically enabled across the focus transition.
	h.textInputEnabled = false
	h.textInputPending = textInputPending{}
	h.textInputMu.Unlock()
}

func (h *LibwaylandHandle) MarkTextInputLeave() {
	if h == nil {
		return
	}
	h.textInputMu.Lock()
	h.textInputEntered = false
	h.textInputEnabled = false
	h.textInputPending = textInputPending{}
	h.textInputMu.Unlock()
}

// SetTextInputEnabled sends enable/disable. State setters are ignored while
// disabled; callers replay the explicit cursor/content/surrounding state after
// enabling so no surrounding text is retained while IME is inactive.
func (h *LibwaylandHandle) SetTextInputEnabled(enabled bool) {
	if h == nil {
		return
	}
	h.displayMu.Lock()
	h.textInputMu.Lock()
	if !h.textInputSupported || h.textInput == 0 || (enabled && h.textInputEnabled) {
		h.textInputMu.Unlock()
		h.displayMu.Unlock()
		return
	}
	h.textInputEnabled = enabled
	textInput := h.textInput
	if !enabled {
		h.textInputPending = textInputPending{}
	}
	h.textInputMu.Unlock()
	if enabled {
		h.marshalVoid(textInput, 1) // enable
	} else {
		h.marshalVoid(textInput, 2) // disable
	}
	_ = h.flushWithRetry()
	h.displayMu.Unlock()
}

// SetTextInputCursorArea updates the logical-DIP cursor rectangle and commits
// the request atomically with the other text-input state setters.
func (h *LibwaylandHandle) SetTextInputCursorArea(area gpucontext.IMECursorArea) {
	if h == nil {
		return
	}
	x, okX := textInputCoordinate(area.X)
	y, okY := textInputCoordinate(area.Y)
	w, okW := textInputCoordinate(area.Width)
	ht, okH := textInputCoordinate(area.Height)
	if !okX || !okY || !okW || !okH {
		return
	}
	h.withTextInputState(func(proxy uintptr) {
		h.marshalVoid(proxy, 6, uintptr(x), uintptr(y), uintptr(w), uintptr(ht))
	})
}

// SetTextInputContentType sends the v3 content purpose and hint bitmask.
// gpucontext intentionally uses the same enum values as this protocol. An
// unknown purpose is normalized to normal as required by the contract.
func (h *LibwaylandHandle) SetTextInputContentType(purpose gpucontext.ContentPurpose, hints gpucontext.ContentHint) {
	if h == nil {
		return
	}
	if purpose > gpucontext.ContentPurposeChat {
		purpose = gpucontext.ContentPurposeNormal
	}
	h.withTextInputState(func(proxy uintptr) {
		h.marshalVoid(proxy, 5, uintptr(uint32(hints)), uintptr(uint32(purpose)))
	})
}

// SetTextInputSurrounding sends UTF-8 context and byte offsets. The temporary
// C string is kept alive until the synchronous marshal call returns and is not
// retained by this backend after the request is queued.
func (h *LibwaylandHandle) SetTextInputSurrounding(text gpucontext.IMESurroundingText) {
	if h == nil || !text.IsValid() || len(text.Text) > math.MaxUint32 || text.Cursor > math.MaxUint32 || text.Anchor > math.MaxUint32 {
		return
	}
	data := make([]byte, len(text.Text)+1)
	copy(data, text.Text)
	h.withTextInputState(func(proxy uintptr) {
		h.marshalVoid(proxy, 3, uintptr(unsafe.Pointer(&data[0])), uintptr(uint32(text.Cursor)), uintptr(uint32(text.Anchor)))
		runtime.KeepAlive(data)
	})
}

// withTextInputState sends one or more state requests followed by commit. The
// display lock prevents render-thread WSI calls from racing this transaction.
// A disabled or unavailable protocol object is a deliberate no-op.
func (h *LibwaylandHandle) withTextInputState(fn func(proxy uintptr)) {
	h.displayMu.Lock()
	h.textInputMu.Lock()
	if !h.textInputSupported || h.textInput == 0 || !h.textInputEnabled {
		h.textInputMu.Unlock()
		h.displayMu.Unlock()
		return
	}
	proxy := h.textInput
	fn(proxy)
	h.marshalVoid(proxy, 7) // commit
	_ = h.flushWithRetry()
	h.textInputMu.Unlock()
	h.displayMu.Unlock()
}

func textInputCoordinate(value float64) (int32, bool) {
	if value < 0 || math.IsNaN(value) || math.IsInf(value, 0) || value > math.MaxInt32 {
		return 0, false
	}
	rounded := math.Round(value)
	if rounded > math.MaxInt32 {
		return 0, false
	}
	return int32(rounded), true
}

// DestroyTextInput releases protocol objects before their wl_seat is
// destroyed. It is safe to call more than once.
func (h *LibwaylandHandle) DestroyTextInput() {
	if h == nil {
		return
	}
	h.displayMu.Lock()
	h.textInputMu.Lock()
	manager := h.textInputManager
	textInput := h.textInput
	h.textInputManager = 0
	h.textInput = 0
	h.textInputSupported = false
	h.textInputEnabled = false
	h.textInputEntered = false
	h.textInputPending = textInputPending{}
	h.textInputMu.Unlock()
	if textInput == 0 && manager == 0 {
		h.displayMu.Unlock()
		return
	}

	textInputHandlesMu.Lock()
	delete(textInputHandles, textInput)
	textInputHandlesMu.Unlock()

	if textInput != 0 {
		h.marshalVoid(textInput, 0) // destroy
	}
	if manager != 0 {
		h.marshalVoid(manager, 0) // destroy
	}
	_ = h.flushWithRetry()
	if textInput != 0 {
		h.proxyDestroy(textInput)
	}
	if manager != 0 {
		h.proxyDestroy(manager)
	}
	h.displayMu.Unlock()
}

func textInputForProxy(proxy uintptr) *LibwaylandHandle {
	textInputHandlesMu.Lock()
	h := textInputHandles[proxy]
	textInputHandlesMu.Unlock()
	return h
}

func textInputEnterCb(data, proxy uintptr) {
	h := textInputForProxy(proxy)
	if h == nil {
		return
	}
	h.MarkTextInputEnter()
	if h.inputCallbacks != nil && h.inputCallbacks.OnTextInputEnter != nil {
		h.inputCallbacks.OnTextInputEnter()
	}
}

func textInputLeaveCb(data, proxy uintptr) {
	h := textInputForProxy(proxy)
	if h == nil {
		return
	}
	h.MarkTextInputLeave()
	if h.inputCallbacks != nil && h.inputCallbacks.OnTextInputLeave != nil {
		h.inputCallbacks.OnTextInputLeave()
	}
}

func textInputPreeditCb(data, proxy, textPtr, cursorBegin, cursorEnd uintptr) {
	h := textInputForProxy(proxy)
	if h == nil {
		return
	}
	text, ok := textInputCString(textPtr)
	if !ok {
		return
	}
	h.textInputMu.Lock()
	h.textInputPending.hasPreedit = true
	h.textInputPending.preeditText = text
	h.textInputPending.cursorBegin = int32(cursorBegin)
	h.textInputPending.cursorEnd = int32(cursorEnd)
	h.textInputMu.Unlock()
}

func textInputCommitCb(data, proxy, textPtr uintptr) {
	h := textInputForProxy(proxy)
	if h == nil {
		return
	}
	text, ok := textInputCString(textPtr)
	if !ok {
		return
	}
	h.textInputMu.Lock()
	// A compositor must send at most one commit_string per done transaction.
	// Keeping the first payload makes duplicate protocol callbacks harmless and
	// prevents duplicate committed text at the application boundary.
	if !h.textInputPending.commitSet {
		h.textInputPending.commitSet = true
		h.textInputPending.commitText = text
	}
	h.textInputMu.Unlock()
}

func textInputDeleteCb(data, proxy, before, after uintptr) {
	h := textInputForProxy(proxy)
	if h == nil {
		return
	}
	h.textInputMu.Lock()
	if !h.textInputPending.deleteSet {
		h.textInputPending.deleteSet = true
		h.textInputPending.deleteBefore = uint32(before)
		h.textInputPending.deleteAfter = uint32(after)
	}
	h.textInputMu.Unlock()
}

func textInputDoneCb(data, proxy, serial uintptr) {
	h := textInputForProxy(proxy)
	if h == nil {
		return
	}
	h.textInputMu.Lock()
	pending := h.textInputPending
	h.textInputPending = textInputPending{}
	h.textInputMu.Unlock()
	if h.inputCallbacks == nil || h.inputCallbacks.OnTextInputDone == nil {
		return
	}
	h.inputCallbacks.OnTextInputDone(TextInputUpdate{
		HasPreedit:   pending.hasPreedit,
		PreeditText:  pending.preeditText,
		CursorBegin:  pending.cursorBegin,
		CursorEnd:    pending.cursorEnd,
		HasCommit:    pending.commitSet,
		CommitText:   pending.commitText,
		HasDelete:    pending.deleteSet,
		DeleteBefore: pending.deleteBefore,
		DeleteAfter:  pending.deleteAfter,
	})
}

// textInputCString copies one bounded, NUL-terminated protocol string and
// rejects malformed UTF-8. A protocol peer cannot legitimately send an
// unbounded payload; the limit also protects event dispatch from hostile data.
func textInputCString(ptr uintptr) (string, bool) {
	if ptr == 0 {
		return "", false
	}
	p := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	const maxLen = 1 << 20
	data := unsafe.Slice((*byte)(p), maxLen)
	for i, b := range data {
		if b == 0 {
			text := string(data[:i])
			return text, utf8.ValidString(text)
		}
	}
	return "", false
}
